'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export const translations = {
  en: {
    'Sign in': 'Sign in',
    'Sign In': 'Sign In',
    'Sign up': 'Sign up',
    'Sign Up': 'Sign Up',
    'Sign out': 'Sign out',
    'Password': 'Password',
    'Confirm Password': 'Confirm Password',
    'Email': 'Email',
    'Full Name': 'Full Name',
    'Remember me': 'Remember me',
    'Forgot your password?': 'Forgot your password?',
    'Already have an account?': 'Already have an account?',
    "Don't have an account?": "Don't have an account?",
    'Create Account': 'Create Account',
    'Password Requirements:': 'Password Requirements:',
    'At least 6 characters': 'At least 6 characters',
    'At least one number': 'At least one number',
    'Check your email to confirm your account': 'Check your email to confirm your account',
    'Failed to create account': 'Failed to create account',
    'AI Chat': 'AI Chat',
    'Go to admin': 'Go to admin',
    'Subscribe to Our Newsletter': 'Subscribe to Our Newsletter',
    'Regular updates about our services': 'Regular updates about our services',
    'Special offers and promotions': 'Special offers and promotions',
    'Industry news and insights': 'Industry news and insights',
    'Subscribe Now': 'Subscribe Now',
    'About Us': 'About Us',
    'Services': 'Services',
    'FAQ': 'FAQ',
    'How It Works': 'How It Works',
    'Support': 'Support',
    'Example Company Name': 'Example Company Name',
    '123 Example Street, City 12345': '123 Example Street, City 12345',
    'ID: 12345678': 'ID: 12345678',
    'Privacy Policy': 'Privacy Policy',
    'Terms of Service': 'Terms of Service',
    'Example Company © 2025': 'Example Company © 2025',
    'Welcome back': 'Welcome back',
    'Dive into the enhanced features and capabilities tailored for your development.': 'Dive into the enhanced features and capabilities tailored for your development.',
    'Enhanced Security': 'Enhanced Security',
    'State-of-the-art security for your apps.': 'State-of-the-art security for your apps.',
    'Blazing Fast': 'Blazing Fast',
    'Optimized for speed, making your apps run smoother.': 'Optimized for speed, making your apps run smoother.',
    'Developer Friendly': 'Developer Friendly',
    'Easy to use API and thorough documentation.': 'Easy to use API and thorough documentation.',
    'Cloud Integration': 'Cloud Integration',
    'Seamless cloud capabilities with Supabase.': 'Seamless cloud capabilities with Supabase.',
    'Easy Integration': 'Easy Integration',
    'Simple steps to integrate with your Next.js app.': 'Simple steps to integrate with your Next.js app.',
    'Explore AI Chat': 'Explore AI Chat',
    'Chats': 'Chats',
    'Files': 'Files',
    'Yesterday': 'Yesterday',
    'Last 7 days': 'Last 7 days',
    'Last 30 days': 'Last 30 days',
    'Chat with our AI Assistant': 'Chat with our AI Assistant',
    'Experience the power of AI-driven conversations with our chat template. Ask questions on any topic and get informative responses instantly.': 'Experience the power of AI-driven conversations with our chat template. Ask questions on any topic and get informative responses instantly.',
    'Start chatting now and enjoy the AI experience!': 'Start chatting now and enjoy the AI experience!',
    'Type your message...': 'Type your message...',
    'Select model:': 'Select model:',
    'Drag files here': 'Drag files here',
    'Or': 'Or',
    'Browse': 'Browse',
    'Supported formats: PDF, DOCX (Max {MAX_TOTAL_FILES} files)': 'Supported formats: PDF, DOCX (Max {MAX_TOTAL_FILES} files)',
    'Note that files with more than approximately 600 pages are not currently supported.': 'Note that files with more than approximately 600 pages are not currently supported.',
    'Create a new conversation': 'Create a new conversation',
    'View uploaded files': 'View uploaded files',
    'View chat history': 'View chat history',
    'Admin Dashboard': 'Admin Dashboard',
    'Total Users': 'Total Users',
    'Total Documents': 'Total Documents',
    'Analytics': 'Analytics',
    'View Reports': 'View Reports',
    'Overview': 'Overview',
    'Users': 'Users',
    'Common Documents': 'Common Documents',
    'Lawyers Documents': 'Lawyers Documents',
    'User Management': 'User Management',
    'Name': 'Name',
    'Role': 'Role',
    'Premium Access': 'Premium Access',
    'Actions': 'Actions',
    'Enter lawyers\' email': 'Enter lawyers\' email',
    'Invite Lawyer': 'Invite Lawyer',
    'Admin': 'Admin',
    'Lawyer': 'Lawyer',
    'Delete': 'Delete',
    'Title': 'Title',
    'AI Title': 'AI Title',
    'Pages': 'Pages',
    'Created At': 'Created At',
    'Uploaded by': 'Uploaded by',
    'Search documents...': 'Search documents...',
    'Preview': 'Preview',
    'Download': 'Download',
    'Lawyer Documents': 'Lawyer Documents',
    'User/Document Analytics': 'User/Document Analytics',
    'User Document Pages': 'User Document Pages',
    'Total Pages by User': 'Total Pages by User',
    'Feature 1': 'Feature 1',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl, nec aliquam nisl nisl sit amet nisl.': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl, nec aliquam nisl nisl sit amet nisl.',
    'Feature 2': 'Feature 2',
    'Praesent et eros eu felis eleifend egestas. Nullam at dolor quis ante porta tincidunt. Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl.': 'Praesent et eros eu felis eleifend egestas. Nullam at dolor quis ante porta tincidunt. Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl.',
    'Feature 3': 'Feature 3',
    'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl.': 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl.',
    'Free Trial': 'Free Trial',
    'Ut ornare lectus sit amet est placerat, nec elementum arcu dignissim. Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl, nec aliquam nisl nisl sit amet nisl.': 'Ut ornare lectus sit amet est placerat, nec elementum arcu dignissim. Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl, nec aliquam nisl nisl sit amet nisl.',
    'Empower Your Next.js App with Supabase Auth': 'Empower Your Next.js App with Supabase Auth',
    'Our library seamlessly integrates with Next.js 14, offering server-side rendering support and efficient data fetching with React Server Components.': 'Our library seamlessly integrates with Next.js 14, offering server-side rendering support and efficient data fetching with React Server Components.',
    'Get Started Now': 'Get Started Now',
    'Discover Our Features': 'Discover Our Features',
    'Harnessing Advanced AI for Better Insights and Efficient Operations': 'Harnessing Advanced AI for Better Insights and Efficient Operations',
    'Example Company': 'Example Company',
    'Contact': 'Contact',
    'Information:': 'Information:',
    'John Doe': 'John Doe',
    'Successfully logged in': 'Successfully logged in',
    'Invalid input credentials': 'Invalid input credentials',
    'Invalid email or password': 'Invalid email or password',
    'Successfully signed out': 'Successfully signed out',
    'Failed to sign out': 'Failed to sign out',
    'Check your email to continue the password reset process': 'Check your email to continue the password reset process',
    'Sign in to save and view your chats': 'Sign in to save and view your chats',
    'Today': 'Today',
    'Last 2 month': 'Last 2 month',
    'Older': 'Older',
    'Loading...': 'Loading...',
    'Load More': 'Load More',
    'Open menu': 'Open menu',
    'Close': 'Close',
    'Delete Chat': 'Delete Chat',
    'Cancel': 'Cancel',
    'Are you sure you want to delete this chat?': 'Are you sure you want to delete this chat?',
    'Share': 'Share',
    'Rename': 'Rename',
    'Rename Chat': 'Rename Chat',
    'Save': 'Save',
    'Search uploaded documents': 'Search uploaded documents',
    'Keywords:': 'Keywords:',
    'Search has been completed.': 'Search has been completed.',
    'Searching...': 'Searching...',
    'Reasoning': 'Reasoning',
    'Upload Timeline': 'Upload Timeline',
    'document': 'document',
    'available': 'available',
    'Uploaded By': 'Uploaded By',
    'No documents match your search': 'No documents match your search',
    'No documents available': 'No documents available',
    'New': 'New',
    'Unknown admin': 'Unknown admin',
    'Unknown user': 'Unknown user',
    'N/A': 'N/A',
    'Unnamed User': 'Unnamed User',
    'No users found': 'No users found',
    'Sending...': 'Sending...',
    "Enter lawyer's email": "Enter lawyer's email",
    'Total Pages': 'Total Pages',
    'Admin Uploads': 'Admin Uploads',
    'User Uploads': 'User Uploads',
    'Document Uploads Over Time': 'Document Uploads Over Time',
  },
  ar: {
    'Sign in': 'تسجيل الدخول',
    'Sign In': 'تسجيل الدخول',
    'Sign up': 'تسجيل',
    'Sign out': 'تسجيل خروج',
    'Password': 'كلمة المرور',
    'Confirm Password': 'تأكيد كلمة المرور',
    'Email': 'البريد الإلكتروني',
    'Full Name': 'الاسم الكامل',
    'Remember me': 'تذكرني',
    'Forgot your password?': 'نسيت كلمة المرور؟',
    'Already have an account?': 'لديك حساب بالفعل؟',
    "Don't have an account?": "ليس لديك حساب؟",
    'Create Account': 'إنشاء حساب',
    'Password Requirements:': 'متطلبات كلمة المرور:',
    'At least 6 characters': 'على الأقل 6 أحرف',
    'At least one number': 'رقم واحد على الأقل',
    'Check your email to confirm your account': 'تحقق من بريدك الإلكتروني لتأكيد حسابك',
    'Failed to create account': 'فشل في إنشاء الحساب',
    'AI Chat': 'الدردشة بالذكاء الاصطناعي',
    'Go to admin': 'الذهاب إلى لوحة التحكم',
    'Subscribe to Our Newsletter': 'اشترك في نشرتنا الإخبارية',
    'Regular updates about our services': 'تحديثات منتظمة حول خدماتنا',
    'Special offers and promotions': 'عروض خاصة وترقيات',
    'Industry news and insights': 'أخبار الصناعة ورؤى',
    'Subscribe Now': 'اشترك الآن',
    'About Us': 'معلومات عنا',
    'Services': 'الخدمات',
    'FAQ': 'الأسئلة الشائعة',
    'How It Works': 'كيف يعمل',
    'Support': 'الدعم',
    'Example Company Name': 'اسم الشركة مثال',
    '123 Example Street, City 12345': '123 شارع مثال، المدينة 12345',
    'ID: 12345678': 'الهوية: 12345678',
    'Privacy Policy': 'سياسة الخصوصية',
    'Terms of Service': 'شروط الخدمة',
    'Example Company © 2025': 'شركة مثال © 2025',
    'Welcome back': 'مرحباً بعودتك',
    'Enhanced Security': 'أمان محسن',
    'State-of-the-art security for your apps.': 'أحدث أنظمة الأمان لتطبيقاتك.',
    'Blazing Fast': 'سريع للغاية',
    'Optimized for speed, making your apps run smoother.': 'مُحسَّن للسرعة، مما يجعل تطبيقاتك تعمل بسلاسة أكبر.',
    'Developer Friendly': 'صديق للمطورين',
    'Easy to use API and thorough documentation.': 'واجهة برمجة تطبيقات سهلة الاستخدام ووثائق شاملة.',
    'Cloud Integration': 'تكامل السحابة',
    'Seamless cloud capabilities with Supabase.': 'قدرات سحابية سلسة مع Supabase.',
    'Easy Integration': 'تكامل سهل',
    'Simple steps to integrate with your Next.js app.': 'خطوات بسيطة للدمج مع تطبيق Next.js الخاص بك.',
    'Explore AI Chat': 'استكشف الدردشة بالذكاء الاصطناعي',
    'Chats': 'الدردشات',
    'Files': 'الملفات',
    'Yesterday': 'الأمس',
    'Last 7 days': 'آخر 7 أيام',
    'Last 30 days': 'آخر 30 يومًا',
    'Chat with our AI Assistant': 'تحدث مع مساعدنا بالذكاء الاصطناعي',
    'Experience the power of AI-driven conversations with our chat template. Ask questions on any topic and get informative responses instantly.': 'جرب قوة المحادثات المدعومة بالذكاء الاصطناعي مع نموذج الدردشة الخاص بنا. اطرح أسئلة حول أي موضوع واحصل على ردود إعلامية على الفور.',
    'Start chatting now and enjoy the AI experience!': 'ابدأ الدردشة الآن واستمتع بتجربة الذكاء الاصطناعي!',
    'Type your message...': 'اكتب رسالتك...',
    'Select model:': 'اختر نموذجًا:',
    'Drag files here': 'اسحب الملفات هنا',
    'Or': 'أو',
    'Browse': 'تصفح',
    'Supported formats: PDF, DOCX (Max {MAX_TOTAL_FILES} files)': 'التنسيقات المدعومة: PDF، DOCX (بحد أقصى {MAX_TOTAL_FILES} ملفات)',
    'Note that files with more than approximately 600 pages are not currently supported.': 'لاحظ أن الملفات التي تحتوي على أكثر من 600 صفحة تقريبًا غير مدعومة حاليًا.',
    'Create a new conversation': 'إنشاء محادثة جديدة',
    'View uploaded files': 'عرض الملفات المرفوعة',
    'View chat history': 'عرض سجل الدردشة',
    'Admin Dashboard': 'لوحة تحكم المشرف',
    'Total Users': 'إجمالي المستخدمين',
    'Total Documents': 'إجمالي المستندات',
    'Analytics': 'التحليلات',
    'View Reports': 'عرض التقارير',
    'Overview': 'نظرة عامة',
    'Users': 'المستخدمين',
    'Common Documents': 'المستندات العامة',
    'Lawyers Documents': 'مستندات المحامين',
    'User Management': 'إدارة المستخدمين',
    'Name': 'الاسم',
    'Role': 'الدور',
    'Premium Access': 'وصول مميز',
    'Actions': 'إجراءات',
    'Enter lawyers\' email': 'أدخل بريد المحامي الإلكتروني',
    'Invite Lawyer': 'دعوة محام',
    'Admin': 'مشرف',
    'Lawyer': 'محام',
    'Delete': 'حذف',
    'Title': 'العنوان',
    'AI Title': 'عنوان الذكاء الاصطناعي',
    'Pages': 'الصفحات',
    'Created At': 'تم الإنشاء في',
    'Uploaded by': 'تم الرفع بواسطة',
    'Search documents...': 'ابحث في المستندات...',
    'Preview': 'معاينة',
    'Download': 'تحميل',
    'Lawyer Documents': 'مستندات المحامين',
    'User/Document Analytics': 'تحليلات المستخدم/المستند',
    'User Document Pages': 'صفحات مستندات المستخدم',
    'Total Pages by User': 'إجمالي الصفحات حسب المستخدم',
    'Feature 1': 'الميزة 1',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl, nec aliquam nisl nisl sit amet nisl.': 'لوريم إيبسوم دولور سيت أميت، consectetur adipiscing إيليت. لكن يا يوسف، لا يوجد حب لبعض التنورات، ولا يوجد حب لبعض الأصدقاء، ولا يوجد حب لبعض الأصدقاء، ولا يوجد حب لبعض الأصدقاء.',
    'Feature 2': 'الميزة 2',
    'Praesent et eros eu felis eleifend egestas. Nullam at dolor quis ante porta tincidunt. Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl.': 'إنه موجود ويريد إيروس إي كات إليفيند. لا يوجد أي ألم على الإطلاق، من أمام الباب؟ لكن يا يوس مود، لا يوجد حب لبعض التنورات، لبعض اللاعبين، لبعض اللاعبين.',
    'Feature 3': 'الميزة 3',
    'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl.': 'الدهليز أمام نفسه أولاً في فم العيادة الحزن والقروح وضعت أسرة الرعاية؛ لكن يا يوس مود، لا يوجد حب لبعض التنورات، لبعض اللاعبين، لبعض اللاعبين.',
    'Free Trial': 'نسخة تجريبية مجانية',
    'Ut ornare lectus sit amet est placerat, nec elementum arcu dignissim. Sed euismod, nulla sit amet aliquam lacinia, nisl nisl aliquam nisl, nec aliquam nisl nisl sit amet nisl.': 'تزيين السرير هو أن تكون عاشقًا، وهو مجرد مكان مؤقت، وليس عنصرًا من عناصر قوس الكرامة. لكن يا يوسف، لا يوجد حب لبعض التنورات، ولا يوجد حب لبعض الأصدقاء، ولا يوجد حب لبعض الأصدقاء، ولا يوجد حب لبعض الأصدقاء.',
    'Empower Your Next.js App with Supabase Auth': 'قم بتمكين تطبيق Next.js الخاص بك باستخدام Supabase Auth',
    'Our library seamlessly integrates with Next.js 14, offering server-side rendering support and efficient data fetching with React Server Components.': 'تتكامل مكتبتنا بسلاسة مع Next.js 14، مما يوفر دعمًا للعرض من جانب الخادم وجلب البيانات بكفاءة باستخدام مكونات React Server.',
    'Dive into the enhanced features and capabilities tailored for your development.': 'انغمس في الميزات والقدرات المحسنة المصممة خصيصًا لتطويرك.',
    'Get Started Now': 'ابدأ الآن',
    'Discover Our Features': 'اكتشف ميزاتنا',
    'Harnessing Advanced AI for Better Insights and Efficient Operations': 'تسخير الذكاء الاصطناعي المتقدم لتحقيق رؤى أفضل وعمليات فعالة',
    'Example Company': 'شركة مثال',
    'Contact': 'اتصال',
    'Information:': 'معلومة:',
    'Sign Up': 'اشتراك',
    'John Doe': 'جون دو',
    'Successfully logged in': 'تم تسجيل الدخول بنجاح',
    'Invalid input credentials': 'بيانات اعتماد الإدخال غير صالحة',
    'Invalid email or password': 'البريد الإلكتروني أو كلمة المرور غير صالحة',
    'Successfully signed out': 'تم تسجيل الخروج بنجاح',
    'Failed to sign out': 'فشل في تسجيل الخروج',
    'Check your email to continue the password reset process': 'تحقق من بريدك الإلكتروني لمواصلة عملية إعادة تعيين كلمة المرور',
    'Sign in to save and view your chats': 'قم بتسجيل الدخول لحفظ محادثاتك وعرضها',
    'Today': 'اليوم',
    'Last 2 month': 'الشهرين الماضيين',
    'Older': 'أكبر سنا',
    'Loading...': 'تحميل...',
    'Load More': 'تحميل المزيد',
    'Open menu': 'افتح القائمة',
    'Close': 'يغلق',
    'Delete Chat': 'حذف الدردشة',
    'Cancel': 'يلغي',
    'Are you sure you want to delete this chat?': 'هل أنت متأكد أنك تريد حذف هذه الدردشة؟',
    'Share': 'يشارك',
    'Rename': 'إعادة التسمية',
    'Rename Chat': 'إعادة تسمية الدردشة',
    'Save': 'يحفظ',
    'Search uploaded documents': 'البحث في المستندات التي تم تحميلها',
    'Keywords:': 'الكلمات الرئيسية:',
    'Search has been completed.': 'تم الانتهاء من البحث',
    'Searching...': 'انا ابحث عن...',
    'Reasoning': 'الاستدلال',
    'Upload Timeline': 'الجدول الزمني للتحميل',
    'document': 'وثيقة',
    'available': 'متاح',
    'Uploaded By': 'تم الرفع بواسطة',
    'No documents match your search': 'لا توجد مستندات تطابق بحثك',
    'No documents available': 'لا توجد مستندات متاحة',
    'New': 'جديد',
    'Unknown admin': 'مسؤول غير معروف',
    'Unknown user': 'مستخدم غير معروف',
    'N/A': 'غير متوفر',
    'Unnamed User': 'مستخدم غير مسمى',
    'No users found': 'لم يتم العثور على أي مستخدمين',
    'Sending...': 'إرسال...',
    "Enter lawyer's email": "أدخل البريد الإلكتروني للمحامي",
    'Total Pages': 'إجمالي الصفحات',
    'Admin Uploads': 'تحميلات الإدارة',
    'User Uploads': 'تحميلات المستخدم',
    'Document Uploads Over Time': 'تحميل المستندات بمرور الوقت',
  }
};

type Language = 'en' | 'ar';
type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  dir: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  const t = (key: TranslationKey): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}